library(unitizer)
unitize("tests/interactive/unitizer/unitizer.tests.R")
unitize("tests/interactive/unitizer/unitizer1.tests.R", "tests/interactive/unitizer/unitizer.tests.rds")
unitize("tests/interactive/unitizer/unitizer2.tests.R", "tests/interactive/unitizer/unitizer.tests.rds")
unitize("tests/interactive/unitizer/unitizer3.tests.R", "tests/interactive/unitizer/unitizer.tests.rds")