library(testthat)

test_dir("testthat")
# test_file("testthat/testthat.browse.R")
# test_file("testthat/testthat.capture.R")
# test_file("testthat/testthat.change.R")
# test_file("testthat/testthat.demo.R")
# test_file("testthat/testthat.exec.R")
# test_file("testthat/testthat.get.R")
# test_file("testthat/testthat.handledruns.R")
# test_file("testthat/testthat.item.R")
# test_file("testthat/testthat.list.R")
# test_file("testthat/testthat.misc.R")
# test_file("testthat/testthat.parse.R")
# test_file("testthat/testthat.repairenvs.R")
# test_file("testthat/testthat.search.R")
# test_file("testthat/testthat.section.R")
# test_file("testthat/testthat.shim.R")
# test_file("testthat/testthat.state.R")
# test_file("testthat/testthat.text.R")
# test_file("testthat/testthat.translate.R")
# test_file("testthat/testthat.upgrade.R")
# test_file("testthat/testthat.zzrunlast.R")
