---
title: "unitizeR - Table of Contents"
author: "Brodie Gaslam"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette

vignette: >
  %\VignetteIndexEntry{Table of Contents}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

## TL;DR (Prologue)

`unitizer` bakes in a lot of contextual help so you can get started using it without wading into this rather lengthy vignette.

The best way to get started is to review the interactive demo (with a [companion vignette](02democompanion.html) if you are into documentation):
```
library(unitizer)
demo(unitizer)
```
Or alternative, review the [introduction vignette](00introduction.Rmd).

## Table of Contents

### Introduction

The [introduction vignette](01introduction.html) Explains the motivation for developing `unitizer`, compares it to other unit testing frameworks, and provides a quick start guide.

### Demo Companion

The [demo companion vignette](02democompanion.html) provides additional details and documentation for the included interactive demo.

### Details on Tests

The [details on tests vignette](03tests.html) delves into the details of what constitutes a test in `unitizer`, how to modify how new tests are compared to reference values, how to organize your tests into sections, how to test different aspects of expression evaluation (e.g. stdout, stderr, etc.).

### Interactive Environment

The [interactive environment vignette](04interactiveenvironment.html) reviews the `unitizer` prompt, highlights differences with the standard R prompt, explains the different `unitizer` commands, discussing the `.new` and `.ref` `unitizer` objects, and introduces some of the complexities of `unitizer` evaluation environments.

### Reproducible Tests

By default `unitizer` runs expressions in an environment that does not inherit from `.GlobalEnv` and with a search path reduced to the standard search path of a fresh R session.  The [reproducible tests vignette](05reproducibletests.html) discusses how this is done and potential implications for your tests.

### Nitty Gritty

The [nitty gritty vignette](06nittygritty.html) covers a number of more estoric topics, including:

* More details on `unitizer` environment structure
* Alternate Store Locations
* Overridden functionality
* `unitizer` and eversion control
