---
title: "unitizeR - Reproducible Tests"
author: "Brodie Gaslam"
output:
    rmarkdown::html_vignette:
        toc: true
        css: styles.css

vignette: >
  %\VignetteIndexEntry{05 - Reproducible Tests}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---
## Clean Environments

R's emphasis on avoiding side effects generally means that if you run the same R code more than once you can be relatively certain that you will get the same result each time.  While this is generally true, there are some exceptions.  If you evaluate:
```
x <- x + 5
```
in the global environment, the result will depend on what the value of `x` was prior to evaluation.  Since global environments will often be littered with objects from day to day R use tests are better run elsewhere to avoid conflicts with those objects.

By default `unitize` will run tests in an environment that has the same parent as `.GlobalEnv`:
```
  .GlobalEnv ---> Parent ---> ... --> Base
              /
 UnitizerEnv /
```
This means that objects in the global environment / workspace will not affect your tests.  If you prefer to run your tests in `.GlobalEnv` you can use:
```
unitize(..., env.clean=.GlobalEnv)
```
In order to keep the `unitizer` environment pointed to the parent of `.GlobalEnv` while allowing users to modify the search path with `library`, `attach`, etc., we need to resort to some trickery described in the [implementation section](#implementation).

## Clean Search Paths

One other way tests can change behavior unexpectedly is if the packages / objects attached to the search path change.  A simple example is a test script that relies on package "X", and the user attached that package at some point during interactive use, but forgot to add the requisite `library` call to the test script itself.  During testing, the scripts will work fine, but at some future date if the test scripts are run again they are likely to fail due to the dependency on the package that is not explicitly loaded in the test scripts.

To mitigate this issue, `unitizer` runs on a "trimmed" search path that contains only the packages loaded by default in R (i.e. the packages between `package:base` and `package:stats`).  You will need to explicitly load packages that your tests depend on in your test file (e.g. by using `library()`).  `unitize` will restore the search path to its original state once you complete review.

If you prefer to leave the search path unchanged when you run your tests, use:
```
unitize(..., search.path.clean=FALSE)
```
## Implementation

### Tracing

Unfortunately R does not provide any built-in ways to create clean environments that will remain at the top of the search path, or any straightforward way to evaluate expressions in alternate search paths.  As a result `unitizer` must resort to some tricks to provide this functionality.

`unitizer` will trace `base::library`, `base::attach`, and `base::detach`.  Any time any of those functions is called, `unitizer` will update the parent of the test evaluation environment to be the second environment on the search path (i.e. the parent of `.GlobalEnv`).  By doing this we can ensure that our evaluation environment always has access to any packages that are loaded by the test code.

In addition to resetting the test environment parent, `unitizer` uses the traced functions to record the additions and removal of objects from the search path so that these can be undone once the tests evaluation and review is completed.

### Potential Pitfalls

Clearly overriding such fundemental functions such as `library` / `attach` / `detach` is not good form.  We recognize this, and try to do the overriding in as lightweight a manner as possible.  For `attach` and `detach` we rely primarily on the `exit` parameter to `trace` so that the functions are as close to their original form as possible.  Unfortunately this method is not compatible with `library` since it uses `on.exit`, but again we use an implementation that should be transparent to users.  Additionally, these functions are only traced during `unitizer` execution and are returned to their original state on exit.  The untracing is registered to the `on.exit` of `unitize` so the functions should get untraced even if `unitize` fails.

Aside from the issues raised above, this method is not completely robust.  Any tests that turn tracing off using `tracingState`, or `trace`/`untrace` `library` / `attach` / `detach` will interfere with `unitizer`.  If you must do any of the above you should consider turning off `env.clean` and `search.path.clean` (see `?unitize`).

We considered tracing `trace`/`untrace` and `tracingState` to either prevent or alert about the above issues, but decided that tracing `library` / `attach` / `detach` is already obnoxious enough.  Instead, `unitizer` will attempt to detect whether any problematic `trace` / `untrace` events occurred and will alert you of them.

### Detaching Objects With Environment References

When running `unitize` with `search.path.clean=TRUE`, `unitizer` will restore the original search path by using `library/attach` on any previously detached objects or packages.  This generally works fine with the notable exception of environments containing objects that contain environment references to the search path object itself.

A good example of this is the `tools:rstudio` environment attached to the search path in R sessions run through RStudio.  It contains functions that have for environment the `tools:rstudio` environment.  The problem is that once that environment is detached from the search path, those functions no longer have access to the search path.  Re-attaching the environment to the search path does not solve the problem because `attach` attaches a _copy_ of the environment, not the environment itself.  This new environment will contain the same objects as the original environment, but all the functions therein will have for environment the original detached environment, not the copy that is attached to the search path.

There are a few possible solutions to this problem.  For now we have adopted the simplest which is to keep the `tools:rstudio` environment on the search path even with `search.path.clean=TRUE` (you can over-ride this by changing `search.path.keep`, or, if you have environments on your search path with similar properties, add their names to `search.path.keep`).  Other options include re-attaching with `parent.env<-` instead of `attach`, but messing with the search path in that way seems to be exactly what R core warns about in `?parent.env`:

> The replacement function parent.env<- is extremely dangerous as it can be used to destructively change environments in ways that violate assumptions made by the internal C code. It may be removed in the near future.

Another possibility would be to re-set the environments of functions inside detached environments that have for parent the detached environment, but we do not do this currently.

## Other Reproducibility Problems

### R Global `options`

The `options` function has the potential to change function behavior in ways that could cause tests to produce different results.  `unitizer` does not currently capture options at initial evaluation.

### Package Versions

`unitizer` does not track package versions, so any changes in packages that your tests depend on could cause reproducibility problems.
