---
title: "unitizeR - Vignette Guide"
author: "Brodie Gaslam"
output:
    rmarkdown::html_vignette:
        toc: true
        css: styles.css

vignette: >
  %\VignetteIndexEntry{Vignette Guide}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

## Prologue (TL;DR)

`unitizer` bakes in a lot of contextual help so you can use it without wading into this rather lengthy set of vignettes. The best way to get started is to review the interactive demo (and the [companion vignette](02democompanion.html) if you are into documentation):
```
library(unitizer)
demo(unitizer)
```
Or alternative, review the [introduction vignette](00introduction.Rmd).

## Vignettes

### Introduction

The [introduction vignette](01introduction.html) explains the motivation for developing `unitizer`, compares it to other unit testing frameworks, provides a quick start guide, and highlights some issues you should be aware of when using `unitizer`.

### Demo Companion

The [demo companion vignette](02democompanion.html) provides additional details and documentation for the included interactive demo.

### Details on Tests

The [details on tests vignette](03tests.html) delves into the details of what constitutes a test in `unitizer`, how to modify how new tests are compared to reference values, how to organize your tests into sections, and how to test different aspects of expression evaluation (e.g. stdout, stderr, etc.).

### Interactive Environment

The [interactive environment vignette](04interactiveenvironment.html) reviews the `unitizer` prompt, highlights differences with the standard R prompt, explains the different `unitizer` commands, discussing the `.new` and `.ref` `unitizer` objects, and introduces some of the complexities of `unitizer` evaluation environments.

### Reproducible Tests

By default `unitizer` runs expressions in an environment that does not inherit from `.GlobalEnv` and with a search path reduced to the standard search path of a fresh R session.  The [reproducible tests vignette](05reproducibletests.html) discusses how this is done and potential implications for your tests.

### Esoteric Topics

The [esoteric topics vignette](06nittygritty.html) covers a number of miscellaneous topics, including:

* More details on `unitizer` environment structure
* How `unitizer`s are stored, and implications thereof
* Overridden functionality
* `unitizer` and version control
