#' Retrieve Unitizer
#'
#' If this errors, calling function should abort
#'
#' @keywords internal
#' @param store.id anything for which there is a defined \code{`\link{get_store}`}
#'   method; by default should be the path to a unitizer; if \code{`\link{get_store}`}
#'   returns \code{`FALSE`} then this will create a new unitizer
#' @param par.frame the environment to use as the parent frame for the \code{`unitizer`}
#' @return a \code{`unitizer`} object, or anything, in which case the calling
#'   code should exit

load_unitizer <- function(store.id, par.frame) {

  if(inherits(try(unitizer <- get_store(store.id)), "try-error")) {
    stop(
      "Unable to retrieve/create `unitizer` at location ", store.id,
      "; see prior errors for details."
  ) }
  # Retrieve or create unitizer environment (note that the search path trimming)
  # happens later.  Also note that pack.env$zero.env can still be tracking the
  # top package under .GlobalEnv

  if(identical(unitizer, FALSE)) {
    unitizer <- new("unitizer", id=store.id, zero.env=new.env(parent=par.frame))
  } else if(!is(unitizer, "unitizer")){
    if(!identical(class(store.id), "character"))
      stop("Logic Error: `get_store.", class(store.id)[[1]], "` did not return a unitizer")
    stop("Logic Error: `get_store` did not return a unitizer; contact maintainer.")
  } else if(inherits(try(validObject(unitizer, complete=TRUE)), "try-error")) {
    if(
      inherits(
        version.compare <-
          try(unitizer@version < packageVersion("unitizer"), silent=TRUE),
        "try-error"
      )
    ) {
      stop("Invalid `unitizer`; contact package maintainer")
    } else if (isTRUE(version.compare)) {
      message(
        "You are attempting to load a `unitizer` generated by an older version (",
        unitizer@version, ") of `unitizer` vs. the currently loaded one (",
        packageVersion("unitizer"),"). Do you wish to attempt to upgrade your ",
        "`unitizer` to the new version ([Y]es, [N]o)?"
      )
      help <- paste0(
        "Pressing Y will upgrade your `unitizer` to the newest version if possible"
      )
      act <- unitizer_prompt(
        "Upgrade unitizer", new.env(par.frame), help,
        valid.opts=c(Y="[Y]es", N="[N]o")
      )
      msg <- paste0(
        "If you don't wish to / can't automatically upgrade your unitizer you can re-",
        "run the tests with the version of unitizer you used to generate them in ",
        "the first place to ensure they still pass, manually delete the ",
        "corresponding RDS, and re-run the tests with the new version of `unitizer`."
      )
      if(identical(act, "Y")) {
        if(
          inherits(try(unitizer <- upgrade(unitizer)), "try-error") ||
          inherits(try(validObject(unitizer, complete=TRUE)), "try-error")
        ) {
          stop("Unable to upgrade. ", msg)
        }
        success <- try(set_store(store.id, unitizer))
        if(!inherits(success, "try-error"))
          message("unitizer upgraded; please re-run function")
        return(invisible(success))
      } else {
        stop("Cannot proceed with out of date `unitizer`. ", msg)
      }
    } else {
      stop("Logic Error: unitizer appears corrupted in some way; contact maintainer.")
    }
  }
  unitizer
}
