#' Alter Older unitizer Versions So They Pass Validation in Latest Version
#'
#' Sequentially applies all applicable patches
#'
#' @keywords internal
#' @param object an unitizer object
#' @param ... other arguments
#' @return an upgraded unitizer object

setMethod("upgrade", "unitizer", valueClass="unitizer",
  function(object, par.frame, ...) {
    # - Do We Need To Upgrade --------------------------------------------------

    if(inherits(try(validObject(object, complete=TRUE)), "try-error")) {
      if(
        inherits(
          version.compare <-
            try(object@version < packageVersion("unitizer"), silent=TRUE),
          "try-error"
        )
      ) {
        stop("Invalid `unitizer`; contact package maintainer")
      } else if (isTRUE(version.compare)) {
        message(
          "You are attempting to load a `unitizer` generated by an older version (",
          object@version, ") of `unitizer` vs. the currently loaded one (",
          packageVersion("unitizer"),"). Do you wish to attempt to upgrade your ",
          "`unitizer` to the new version ([Y]es, [N]o)?"
        )
        help <- paste0(
          "Pressing Y will upgrade your `unitizer` to the newest version if possible"
        )
        act <- unitizer_prompt(
          "Upgrade unitizer", new.env(parent=par.frame), help,
          valid.opts=c(Y="[Y]es", N="[N]o")
        )
        msg <- paste0(
          "If you don't wish to / can't automatically upgrade your unitizer you can re-",
          "run the tests with the version of unitizer you used to generate them in ",
          "the first place to ensure they still pass, manually delete the ",
          "corresponding RDS, and re-run the tests with the new version of `unitizer`."
        )
        if(identical(act, "Y")) {
          if(
            inherits(try(object <- upgrade_internal(object)), "try-error") ||
            inherits(try(validObject(object, complete=TRUE)), "try-error")
          ) {
            stop("Unable to upgrade. ", msg)
          }

        } else {
          stop("Cannot proceed with out of date `unitizer`. ", msg)
        }
      } else {
        stop("Logic Error: unitizer appears corrupted in some way; contact maintainer.")
      }
    }
    object
} )
#' Helper function to actually do upgrade
#'
#' @keywords internal

upgrade_internal <- function(object) {
  # - 0.4.3 --------------------------------------------------------------------

  # Need to add tests.conditions.new slot

  if(object@version < "0.4.3") {
    object <- addSlot(object, "tests.conditions.new", logical(length(object@items.new)))
  }
  # - 0.5.2 --------------------------------------------------------------------

  # Need to add sections.ref and section.map.ref, and add a section id slot
  # to all the unitizerItem objects

  if(object@version < "0.5.2") {
    # This adds the reference test section data

    # Add the requisite reference section fields

    ref.len <- length(object@items.ref)
    object <- addSlot(object, "sections.ref", list(new("unitizerSectionNA", length=ref.len)))
    object <- addSlot(object, "section.ref.map", rep(1L, ref.len))

    # Updated changes sub-object

    object@changes <- addSlot(object@changes, "passed", integer(2L))

    # Now add the new section.id field to every item

    object@items.ref@.items <- lapply(
      object@items.ref@.items,
      function(x) addSlot(x, "section.id", NA_integer_)
    )
  }
  # - 0.5.3 --------------------------------------------------------------------

  # Make sure ref item ids are reasonable

  if(object@version < "0.5.3") {
    for(i in seq(len=length(object@items.ref))) object@items.ref[[i]]@id <- i
  }
  # - Done ---------------------------------------------------------------------

  object
}

#' Helper Function To Add A Slot to An Out-of-date S4 Object
#'
#' @keywords internal

addSlot <- function(object, slot.name, slot.value) {
  if(!isS4(object))
    stop("Argument `object` must be an S4 object")
  slots <- slotNames(object)
  slot.vals <- list()
  for(i in slots) {
    if(identical(i, slot.name)) next
    tmp <- try(slot(object, i), silent=TRUE)
    if(!inherits(tmp, "try-error")) {
      slot.vals <- c(slot.vals, setNames(list(tmp), i))  # growing list, but shouldn't be massive
    }
  }
  slot.vals <- c(slot.vals, setNames(list(slot.value), slot.name))
  new.object <- new(class(object))
  for(slot.name in names(slot.vals)) {
    slot(new.object, slot.name) <- slot.vals[[slot.name]]
  }
  new.object
}

